// Generated by okf-parser
import { z } from 'zod';

export const MunicipioSchema = z.object({
  "codigo_ibge": z.string(),
  "description": z.string().optional(),
  "nome": z.string(),
  "title": z.string().optional(),
  "type": z.literal("Municipio"),
  "uf": z.string(),
  "url": z.string().optional()
});

export const UnidadeFederativaSchema = z.object({
  "description": z.string().optional(),
  "nome": z.string(),
  "regiao": z.string(),
  "sigla": z.string(),
  "title": z.string().optional(),
  "type": z.literal("UnidadeFederativa")
});
